language: node_js
node_js:
  - "12"
dist: trusty

branches:
  only:
  - master

cache:
  directories:
    - node_modules

addons:
  chrome: stable
  sonarcloud:
    organization: "speech4j"

before_script: 
  - npm install

script:
  - npm run test-headless
  - sonar-scanner -Dsonar.verbose=true -X
  - npm run build

deploy:
  provider: heroku
  skip_cleanup: true
  keep-history: true
  api-key:
    secure: $HEROKU_API_KEY
  app: speech4jweb

after_deploy:
  - echo "Application Deployed!"