language: node_js
node_js:
  - "12"
dist: trusty
sudo: required
services:
  - docker

cache:
  directories:
    - node_modules

addons:
  chrome: stable
  sonarcloud:
    organization: "speech4j"

branches:
  only:
    - master

before_install:
  - docker build -t speech4j/web-test -f Dockerfile.dev .

before_script: 
  - npm install -g --silent @angular/cli@9.1.0

script:
  - docker run -e CI=true speech4j/web-test -v "$(pwd)"/coverage:/web/coverage/web 55e79f84f759 npm run test-headless
  - sonar-scanner -Dsonar.verbose=true -X
  - npm run build

after_success:
  - docker build -t speech4j/web .
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push speech4j/web

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "speech4jweb"
  env: "Speech4jweb-env"
  bucket_name: "elasticbeanstalk-us-east-2-547860292933"
  bucket_path: "speech4jweb"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: 
    secure: "$AWS_SECRET_KEY"
