language: node_js
node_js:
  - "12"
dist: trusty
sudo: required
services:
  - docker

cache:
  directories:
    - node_modules

addons:
  chrome: stable
  sonarcloud:
    organization: "speech4j"

branches:
  only:
    - master

before_script: 
  - npm install
  - docker build -t speech4j/web-test -f Dockerfile.dev .

script:
  - docker run -e CI=true speech4j/web-test -v "$(pwd)"/coverage:/web/coverage/web 55e79f84f759 npm run test-headless
  - sonar-scanner -Dsonar.verbose=true -X
  - npm run build

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "web"
  env: "webenv"
  bucket_name: "elasticbeanstalk-us-west-2-547860292933"
  bucket_path: "web"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY

after_deploy:
  - echo "Application Deployed!"