language: node_js

node_js:
- '12'

sudo: required

services:
  - docker
  
dist: trusty

branches:
  only:
  - master

addons:
  chrome: stable
  sonarcloud:
    organization: speech4j

before_install:
  - docker build -t speech4j/web-test -f Dockerfile.dev .

script:
  - docker run -it -e CI=true -v "$(pwd)/coverage/web:/coverage/web" speech4j/web-test npm run test-headless
  - sonar-scanner -Dsonar.verbose=true -X

after_success:
  - docker build -t speech4j/web .
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push speech4j/web

deploy:
  provider: heroku
  skip_cleanup: true
  keep-history: true
  app: speech4jweb
  api_key:
    secure: fZLBDGUUwJS6setqj4DDwHCwfr7ybdkSTu7rhEGXLawOFYpUvLkOP/McYBITMh9bOFe59HLsF5mfKb3v7B+xP8qjsTWzdVOB7jWztoEznZgXupcGhAX2DFO0y1SBYOvsg+Tq7623rIYQoqcX6bsATD0drlv1qhS4tjblxLzTZm8L0c4SA1w5JeSzSHL8yS83O9iXeJQKBsqaOA7qNEqmDpU4YGGenAK0FBGWNFnW5uvFFJKg9B/c8F73mXw/u2pMeYU2w8Gop5SIn9I211WA23El5I4LR7rYEvd/8tuW50InpDlL2BVS32hjrZa+xQPIIKFgtR3YssLc23kc/98K0Z9QM52LPlzoZTpGBtDgSK3hYU9ZtVRSRqL2V8m5tYnZehOSkwOfvveirQk1r/DRxk7c7F5KkIQ6GpYqbUbSJT+oCn/UsIirqI1GxFF18H88AsXr2BCgejpPDHKDu291AItLGls6SJQKQsRZCCp2JgIHUqZL60XWNo0kYteNtQyeynq8UhoCBueZFxh+sbT/56EMPXBO/7/U8nvoZ/xRO+VYgmGArpz3opjAusIa6YlXns0PgaCilJHnX64VE2ykioiYBtAfOTWG0bsTViiqcH40M3h1kjRpzQDyPCcN+btNx6qHTUyhmANQHLVpinLaIrJtCBCHZ7KNJsborIlNgUo=

after_deploy:
- echo "Application Deployed!"
