version: '3.7'

services: 
  web-dev:
    container_name: web-dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - '.:/web'
      - '/web/node_modules'
    ports:
      - '4201:4200'



